// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG9BksxUGGmjBHoI7EB2tIgsJJLhXPidw',
    appId: '1:1084212496696:web:33332ba0cab6eddabf19cd',
    messagingSenderId: '1084212496696',
    projectId: 'carebridge-e1eb9',
    authDomain: 'carebridge-e1eb9.firebaseapp.com',
    storageBucket: 'carebridge-e1eb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHY4knNyZ9FUDgjbp9dARsiXOJHDJHo8c',
    appId: '1:1084212496696:android:3135f2d818c80a6ebf19cd',
    messagingSenderId: '1084212496696',
    projectId: 'carebridge-e1eb9',
    storageBucket: 'carebridge-e1eb9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJgF_GtHA6KEEIA9GSGvZAuLyCBRzztc',
    appId: '1:1084212496696:ios:ae10350b3abac11abf19cd',
    messagingSenderId: '1084212496696',
    projectId: 'carebridge-e1eb9',
    storageBucket: 'carebridge-e1eb9.firebasestorage.app',
    iosBundleId: 'com.example.carebridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJgF_GtHA6KEEIA9GSGvZAuLyCBRzztc',
    appId: '1:1084212496696:ios:ae10350b3abac11abf19cd',
    messagingSenderId: '1084212496696',
    projectId: 'carebridge-e1eb9',
    storageBucket: 'carebridge-e1eb9.firebasestorage.app',
    iosBundleId: 'com.example.carebridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG9BksxUGGmjBHoI7EB2tIgsJJLhXPidw',
    appId: '1:1084212496696:web:12fe99fa99373368bf19cd',
    messagingSenderId: '1084212496696',
    projectId: 'carebridge-e1eb9',
    authDomain: 'carebridge-e1eb9.firebaseapp.com',
    storageBucket: 'carebridge-e1eb9.firebasestorage.app',
  );
}
