// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxECP6-FSloeioXT1itJnUHi6f6uZyFAc',
    appId: '1:928643598475:web:8c9cde0da0543061272c8e',
    messagingSenderId: '928643598475',
    projectId: 'carebridge-b5323',
    authDomain: 'carebridge-b5323.firebaseapp.com',
    storageBucket: 'carebridge-b5323.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI1mIkuy9KVDpsvku-Q2Q5T4MISzIm1g4',
    appId: '1:928643598475:android:c52ec2fd667a2906272c8e',
    messagingSenderId: '928643598475',
    projectId: 'carebridge-b5323',
    storageBucket: 'carebridge-b5323.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-FxTSY4-UamGFOnCP9LwPr25uok7dUM',
    appId: '1:928643598475:ios:7b58c57a44d006a3272c8e',
    messagingSenderId: '928643598475',
    projectId: 'carebridge-b5323',
    storageBucket: 'carebridge-b5323.firebasestorage.app',
    iosBundleId: 'com.example.carebridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-FxTSY4-UamGFOnCP9LwPr25uok7dUM',
    appId: '1:928643598475:ios:7b58c57a44d006a3272c8e',
    messagingSenderId: '928643598475',
    projectId: 'carebridge-b5323',
    storageBucket: 'carebridge-b5323.firebasestorage.app',
    iosBundleId: 'com.example.carebridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxECP6-FSloeioXT1itJnUHi6f6uZyFAc',
    appId: '1:928643598475:web:5db6e2d939387b84272c8e',
    messagingSenderId: '928643598475',
    projectId: 'carebridge-b5323',
    authDomain: 'carebridge-b5323.firebaseapp.com',
    storageBucket: 'carebridge-b5323.firebasestorage.app',
  );
}
